name: Deploy App

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/know_hosts
          chmod 644 ~/.ssh/know_hosts

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "ls"

      #- run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls"